# ------------------- Rest layer Deployment ------------------- #
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "sc-rest-layer.fullname" . }}
  labels:
    app: {{ template "sc-rest-layer.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ template "sc-rest-layer.name" . }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "sc-rest-layer.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.global.repository }}/{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        env:
        {{- range $key, $value := .Values.image.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        - name: ELASTIC_SEARCH_URL
          value: {{ .Release.Name }}-elasticsearch-client.default.svc.cluster.local
        - name: ELASTIC_SEARCH_PORT
          value: "9200"
        resources:
          limits:  
            memory: {{ .Values.deployment.resources.maxMem }}
          requests:
            memory: {{ .Values.deployment.resources.minMem }}
        livenessProbe:
          httpGet:
            path: /api
            port: {{ .Values.deployment.containerPort }}
          initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.deployment.livenessProbe.timeoutSeconds }}
          periodSeconds: {{ .Values.deployment.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: /api
            port: {{ .Values.deployment.containerPort }}
          initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.deployment.readinessProbe.timeoutSeconds }}
          periodSeconds: {{ .Values.deployment.readinessProbe.periodSeconds }}