apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "connect-live-info-soccer.fullname" . }}
spec:
  template:
    metadata:
      name: {{ template "connect-live-info-soccer.fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.global.repository }}/{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        {{- range .Values.cronJob.args }}
          - {{ . | quote }}
        {{- end }}
        env:
        {{- range $key, $value := .Values.image.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        - name: KAFKA_REST_EP
          value: "{{ .Release.Name }}-rest-proxy.default.svc.cluster.local:8082"
      restartPolicy: {{ .Values.cronJob.restartPolicy }}
