apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "zookeeper.fullname" . }}
  labels:
    app: {{ include "zookeeper.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
spec:
  selector:
    matchLabels:
      app: {{ include "zookeeper.name" . | quote }}
      release: {{ .Release.Name | quote }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}