# ------------------- SparkUI Proxy1  Deployment ------------------- #
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "default-http-backend.fullname" . }}
  labels:
    app: {{ template "default-http-backend.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ template "default-http-backend.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "default-http-backend.name" . }}
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}/{{ .Values.image.tag }}
        livenessProbe:
          httpGet:
            path: {{ .Values.deployment.livenessPath }}
            port: {{ .Values.deployment.livenessProbePort }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.deployment.livenessProbeInitDelay }}
          timeoutSeconds: {{ .Values.deployment.livenessProbeTimeoutSeconds }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi