apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "kafka.fullname" . }}-kafka-topics-create-hook-{{ randAlphaNum 5 | lower }}
  labels:
    app: {{ template "kafka.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        app: {{ template "kafka.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      containers:
      - name: {{.Chart.Name}}-kafka-topics-create-hook
        image: {{ .Values.global.repository }}/{{ .Values.image.tag }}
        env:
        {{- range $key, $value := .Values.image.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "{{ .Release.Name }}-zookeeper.default.svc.cluster.local:2181"        
        command: ["/scripts/kafka-topics-create.sh"]