#!/bin/bash

# Copyright 2015 The Kubernetes Authors All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

##
# APP_SPARK_ZOOKEEPER_EP Env variable which carries zookeeper url
# APP_SPARK_MASTERS_EPS Env variable which carries spark masters

function join { local IFS="$1"; shift; echo "$*"; }
IFS=', ' read -r -a masterList <<< "$APP_SPARK_MASTERS_EPS"


connect_to_one=false
for j in `seq 1 4`;
do
  for i in "${masterList[@]}"
  do
  	  mHost=`echo $i | cut -f1 -d ':'`
	  echo "$mHost"
	  if ! getent hosts $mHost; then
		  echo "=== Cannot connect to zookeeper node $mHost"
		  echo "=== Sleeping 10s before pod exit."
	  else
	  	connect_to_one=true;
	  	echo "Connected to $mHost.spark"
	  	break
	  fi
	  sleep 10;
  done
done    

if [ "$connect_to_one" = true ] ; then
    exit 0
else
	exit 1
fi
