# ------------------- Download schedules from slingtv ------------------- #
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: download-schedules
spec:
  schedule: "20 5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: download-schedules
            image: registry.sports-cloud.com:5000/sc-job-scheduler:latest
            args:
            - /bin/sh
            - -c
            - /deploy-scheduled-jobs/scheduled-job-driver.sh download-schedules
          restartPolicy: OnFailure
---
# ------------------- Download summary from slingtv ------------------- #
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: download-summary
spec:
  schedule: "40 5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: download-summary
            image: registry.sports-cloud.com:5000/sc-job-scheduler:latest
            args:
            - /bin/sh
            - -c
            - /deploy-scheduled-jobs/scheduled-job-driver.sh download-summary
          restartPolicy: OnFailure
---
# ------------------- Download thuuz from slingtv ------------------- #
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: download-thuuz
spec:
  schedule: "0 */3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: download-thuuz
            image: registry.sports-cloud.com:5000/sc-job-scheduler:latest
            args:
            - /bin/sh
            - -c
            - /deploy-scheduled-jobs/scheduled-job-driver.sh download-thuuz
          restartPolicy: OnFailure
---
# ------------------- Content Match batch job slingtv ------------------- #
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: confluent-connect-content-match
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: download-schedules
            image: registry.sports-cloud.com:5000/sc-job-scheduler:latest
            args:
            - /bin/sh
            - -c
            - /deploy-scheduled-jobs/scheduled-job-driver.sh connect-jobs com.slingmedia.sportscloud.schedulers.KafkaConnectContentMatchJob
          restartPolicy: OnFailure
---
# ------------------- Live Info batch job slingtv ------------------- #
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: confluent-connect-live-info
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: download-schedules
            image: registry.sports-cloud.com:5000/sc-job-scheduler:latest
            args:
            - /bin/sh
            - -c
            - /deploy-scheduled-jobs/scheduled-job-driver.sh connect-jobs com.slingmedia.sportscloud.schedulers.KafkaConnectLiveInfoJob
          restartPolicy: OnFailure
---
# ------------------- Meta batch job slingtv ------------------- #
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: confluent-connect-meta-batch
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: download-schedules
            image: registry.sports-cloud.com:5000/sc-job-scheduler:latest
            args:
            - /bin/sh
            - -c
            - /deploy-scheduled-jobs/scheduled-job-driver.sh connect-jobs com.slingmedia.sportscloud.schedulers.KafkaConnectMetaBatchJob
          restartPolicy: OnFailure
---
# ------------------- MLB Team standings job ------------------- #
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: team-standings-mlb
spec:
  schedule: "30 9 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mlb-team-standings-job
            image: registry.sports-cloud.com:5000/spark-job
            args: ["/opt/spark/dist/bin/spark-submit",
        "--master", "spark://master-0.spark:6066,spark://master-1.spark:6066,spark://master-2.spark:6066",
        "--deploy-mode","cluster",
        "--name","TeamStandingsMetaDataMuncher","--class", "com.slingmedia.sportscloud.offline.batch.impl.MetaDataMuncher" ,
        "--driver-memory", "2G", 
        "--executor-memory", "2G", 
        "--total-executor-cores", "2", 
        "--conf", "spark.es.index.auto.create=true",
        "--conf", "spark.es.resource=sports-cloud/game_schedule",
        "--conf", "spark.es.nodes=elasticsearch.default.svc.cluster.local",
        "--conf", "spark.es.net.http.auth.user=elastic",
        "--conf", "spark.es.net.http.auth.pass=changeme",
        "--conf", "spark.es.write.operation=upsert",
        "--conf", "spark.default.parallelism=4",
        "--conf", "spark.executor.extraJavaOptions=-XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=30  -XX:G1ReservePercent=15 -XX:MaxGCPauseMillis=2000 -XX:+UseCompressedOops",
        "--conf", "spark.serializer=org.apache.spark.serializer.KryoSerializer",
        "--packages","org.apache.spark:spark-sql-kafka-0-10_2.11:2.1.1",
        "/jars/all-spark-jobs.jar" , "TEAMSTANDINGS", "meta_batch" , "team_standings"
        ]
          restartPolicy: OnFailure