# ------------------- MLB Team standings job ------------------- #
apiVersion: batch/v1
kind: Job
metadata:
  name: spark-content-match-nfl
spec:
  template:
    metadata:
      name: spark-content-match-nfl
    spec:
      containers:
      - name: spark-content-match-nfl
        image: registry.sports-cloud.com:5000/spark-job:0.0.1-alpha.3
        imagePullPolicy: IfNotPresent
        command:
          - "/opt/spark/bin/spark-submit"
          - "--master"
          - "spark://sc-apps-dev-spark-master-0.sc-apps-dev-spark-master-hs.default.svc.cluster.local:6066,sc-apps-dev-spark-master-1.sc-apps-dev-spark-master-hs.default.svc.
          - "--deploy-mode"
          - "cluster"
          - "--name"
          - "NflContentDataMuncher"
          - "--class"
          - "com.slingmedia.sportscloud.offline.batch.impl.ContentMatcher"
          - "--driver-memory"
          - "2G"
          - "--executor-memory"
          - "2G"
          - "--total-executor-cores"
          - "2"
          - "--conf"
          - "spark.es.index.auto.create=true"
          - "--conf"
          - "spark.es.resource=sports-cloud/game_schedule"
          - "--conf"
          - "spark.es.nodes=sc-apps-dev-elasticsearch-client.default.svc.cluster.local"
          - "--conf"
          - "spark.es.net.http.auth.user=elastic"
          - "--conf"
          - "spark.es.net.http.auth.pass=changeme"
          - "--conf"
          - "spark.es.write.operation=upsert"
          - "--conf"
          - "spark.default.parallelism=4"
          - "--conf"
          - "spark.executor.extraJavaOptions=-XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=30 -XX:G1ReservePercent=15 -XX:MaxGCPauseMillis=2000 -XX:+UseCompressedOops"
          - "--conf"
          - "spark.serializer=org.apache.spark.serializer.KryoSerializer"
          - "/jars/all-spark-jobs.jar"
          - "content_match_nfl"
          - "game_schedule"
        env:
      restartPolicy: Never