# ------------------- MLB Team standings job ------------------- #
apiVersion: batch/v1
kind: Job
metadata:
  name: spark-content-match-nfl
spec:
  template:
    metadata:
      name: spark-content-match-nfl
    spec:
      containers:
      - name: spark-content-match-soccer
        image: registry.sports-cloud.com:5000/spark-job:0.0.1-alpha.10
        imagePullPolicy: IfNotPresent
        command:
          - "/opt/spark/bin/spark-submit"
          - "--master"
          - "local[4]"
          - "--deploy-mode"
          - "client"
          - "--name"
          - "SoccerContentDataMuncher"
          - "--class"
          - "com.slingmedia.sportscloud.offline.batch.impl.SoccerContentMatcher"
          - "--driver-memory"
          - "2G"
          - "--executor-memory"
          - "2G"
          - "--total-executor-cores"
          - "2"
          - "--conf"
          - "spark.es.index.auto.create=true"
          - "--conf"
          - "spark.es.nodes=sc-apps-dev-elasticsearch-client.default.svc.cluster.local"
          - "--conf"
          - "spark.es.net.http.auth.user=elastic"
          - "--conf"
          - "spark.es.net.http.auth.pass=changeme"
          - "--conf"
          - "spark.es.write.operation=upsert"
          - "--conf"
          - "spark.default.parallelism=4"
          - "--conf"
          - "spark.executor.extraJavaOptions=-XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=30 -XX:G1ReservePercent=15 -XX:MaxGCPauseMillis=2000 -XX:+UseCompressedOops"
          - "--conf"
          - "spark.serializer=org.apache.spark.serializer.KryoSerializer"
          - "/jars/all-spark-jobs.jar"
          - "content_match_soccer"
          - "game_schedule"
        env:
        - name: KAFKA_BROKER_EP
          value: "sc-apps-dev-kafka-0.sc-apps-dev-kafka-hs.default.svc.cluster.local:9092,sc-apps-dev-kafka-1.sc-apps-dev-kafka-hs.default.svc.cluster.local:9092,sc-apps-dev"
        - name: ARTIFACT_SERVER_EP
          value: "sc-apps-dev-artifact-server.default.svc.cluster.local:9082"
      restartPolicy: Never