# ------------------- Logrotate DaemonSet ------------------- #
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "logrotate.fullname" . }}
  labels:
    app: {{ template "logrotate.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "logrotate.name" . }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "logrotate.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.global.repository }}/{{ .Values.image.tag }}
        args:
        {{- range .Values.deployment.command }}
        - {{ . | quote }}
        {{- end }}
        resources:
          limits:  
            cpu: {{ .Values.deployment.resources.maxCpu }}
            memory: {{ .Values.deployment.resources.maxMem }}
          requests:
            cpu: {{ .Values.deployment.resources.minCpu }}
            memory: {{ .Values.deployment.resources.minMem }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log