#!/bin/bash

# Copyright 2015 The Kubernetes Authors All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
connect_to_one=false
for j in `seq 1 4`;
do
  for i in `seq 0 2`;
  do
	  if ! getent hosts master-$i.spark; then
		  echo "=== Cannot resolve the DNS entry for spark-master. Has the service been created yet, and is SkyDNS functional?"
		  echo "=== See http://kubernetes.io/v1.1/docs/admin/dns.html for more details on DNS integration."
		  echo "=== Sleeping 10s before pod exit."
	  else
	  	connect_to_one=true;
	  	echo "Connected to master-$i.spark"
	  	break
	  fi
	  sleep 10;
  done
done    

if [ "$connect_to_one" = true ] ; then
    /opt/spark/sbin/start-slave.sh -d /spark/work --webui-port 8081 master-0.spark:7077,master-1.spark:7077,master-2.spark:7077
	tail -f /opt/spark/logs/spark-*.out
else
	echo 'No connection to any masters'
fi
