FROM confluentinc/cp-kafka-connect:3.2.0
RUN mkdir -p /data/kafka/connect/libs
ADD jars/kafka-schedule-parser-assembly.jar /data/kafka/connect/libs/kafka-schedule-parser-assembly.jar
ADD jars/kafka-schedule-parser-assembly.jar /usr/share/java/kafka/