kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "zeppelin.fullname" . }}-note-store
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi