apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "connect-live-info-mlb.fullname" . }}
  labels:
    app: {{ template "connect-live-info-mlb.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    jobtype: connect-monit-job
spec:
  replicas: {{ .Values.Job.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "connect-live-info-mlb.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }} 
        jobtype: connect-monit-job
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.global.repository }}/{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:  
            cpu: {{ .Values.deployment.resources.maxCpu }}
            memory: {{ .Values.deployment.resources.maxMem }}
          requests:
            cpu: {{ .Values.deployment.resources.minCpu }}
            memory: {{ .Values.deployment.resources.minMem }}
        args:
        {{- range .Values.Job.command }}
        - {{ . | quote }}
        {{- end }}
        env:
        {{- range $key, $value := .Values.image.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        - name: CONNECT_EP
          value: "{{ .Release.Name }}-connect.default.svc.cluster.local:8083"