kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "artifact-server.fullname" . }}-artifacts-store-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi